### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by CarloLucibello** [ozanarkancan/Gym.jl#3]
Hi,
I didn't have the python gym package installed, and Gym.jl failed for me due to a denied user permission when using pip. Attempting a  local install with
```
pip install --user  gym
```
might be a better option for Gym.jl

**Comment by ozanarkancan** [comment]
Hi,

It should already be doing the local installation ([corresponding line](https://github.com/ozanarkancan/Gym.jl/blob/88f17be09d3e264c0caeda399d9211b0d167d382/deps/build.jl#L10)). Can you post the actual error? It might be related with one of the dependencies of the gym package.

**Comment by CarloLucibello** [comment]
Mhmh, I'm sorry I didn't save the error trace and I can't reproduce the permission error I got earlier:
if I uninstall gym and then build Gym.jl, the python package is properly installed. 
I guess you are right though, I remember It was trying to install a dependency when I saw the error

**Comment by ozanarkancan** [comment]
So, I am closing this until the next occurrence of the error.
