### ISSUE TITLE
Tons of warnings/deprecated calls

### ISSUE THREAD

**Issue by jpp46** [ozanarkancan/Gym.jl#6]
When I am using this I get a huge terminal full of warnings at the beginning. It still works so I guess this isn't a big deal but it would be nice to know that the wrapper is up to date.

**Comment by ozanarkancan** [comment]
Thanks for pointing this issue. I guess, the warnings are related with the PyCall package usage. I will fix them.

**Comment by ozanarkancan** [comment]
fixed on the current master
