### ISSUE TITLE
"no such file" error on package add

### ISSUE THREAD

**Issue by HenriDeh** [ozanarkancan/Gym.jl#7]
Command ] add Gym throws the following error in julia 1.1:
 
 Error: Error building `Gym`:
│ ┌ Warning: special characters "#{}()[]<>|&*?~;" should now be quoted in commands
│ │   caller = #shell_parse#351(::String, ::Function, ::String, ::Bool) at shell.jl:100
│ └ @ Base .\shell.jl:100
│ [ Info: Downloading OpenAi gym
│ ERROR: LoadError: IOError: could not spawn `git clone https://github.com/openai/gym.git`: no such file or directory (ENOENT)
│ Stacktrace:
│  [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at .\process.jl:400
│  [2] #505 at .\process.jl:413 [inlined]
│  [3] setup_stdios(::getfield(Base, Symbol("##505#506")){Cmd}, ::Array{Any,1}) at .\process.jl:497
│  [4] _spawn at .\process.jl:412 [inlined]
│  [5] #run#515(::Bool, ::Function, ::Cmd) at .\process.jl:725
│  [6] run(::Cmd) at .\process.jl:724
│  [7] top-level scope at C:\Users\Henri\.julia\packages\Gym\GnwvQ\deps\build.jl:43
│  [8] include at .\boot.jl:326 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1038
│  [10] include(::Module, ::String) at .\sysimg.jl:29
│  [11] include(::String) at .\client.jl:403
│  [12] top-level scope at none:0
│ in expression starting at C:\Users\Henri\.julia\packages\Gym\GnwvQ\deps\build.jl:31
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075

**Comment by ozanarkancan** [comment]
Hi,

I am not sure whether gym supports windows or not. This package executes `git clone https://github.com/openai/gym.git` command on a prompt while installation. So, you must be sure that that command works.

**Comment by HenriDeh** [comment]
Oh Gym does not not support windows indeed. That's too bad. 
Thank you.
